### ISSUE TITLE
Meta data 설정

### ISSUE THREAD

**Issue by sukjae** [sukjae/corona2019#3]
## 해야할 일

- [x] react helmet 설정
- [x] CRA에서 기본으로 생성되는 metadata를 어떻게 활용해야 하는지
- [x] CRA에서 기본으로 생성되는 metadata를 어떻게 덮어쓰는지 (헬멧으로?)
- [x] 추가해야 할 중요한 정보들
